language: cpp
compiler:
    - g++
dist: trusty
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - libboost-all-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - gcc
      - g++
cache:
  apt: true
script: scons install apps samples
branches:
    only:
        - master
notifications:
    email:
        on_success: change
        on_failure: always
