sudo: false

language: cpp

compiler:
    - g++

env:
  - CMAKE_BUILD_TYPE=DEBUG CXX_VERSION=4.9
  - CMAKE_BUILD_TYPE=RELEASE CXX_VERSION=4.9
  - CMAKE_BUILD_TYPE=DEBUG CXX_VERSION=5
  - CMAKE_BUILD_TYPE=RELEASE CXX_VERSION=5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - libboost1.55-all-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - gcc-4.9
      - g++-4.9
      - gcc-5
      - g++-5
      - python-virtualenv
      - python2.7
      - python3.4

cache:
  apt: true

before_script:
  - wget -O /tmp/cmake.sh http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh
  - mkdir -p /tmp/usr
  - sh /tmp/cmake.sh --skip-license --prefix=/tmp/usr
  - virtualenv /tmp/venv
  - /tmp/venv/bin/pip install tox

script:
  - CXX=g++-${CXX_VERSION} /tmp/usr/bin/cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} .
  - make install
  - CPATH=install/include /tmp/venv/bin/tox

after_success:
  - coveralls

branches:
    only:
        - api

notifications:
    email:
        on_success: change
        on_failure: always
