language: python
compiler:
  - clang
env:
  - TOXENV=py27
before_install:
  - sudo apt-cache search libboost
  - sudo apt-get update -qq
  - sudo apt-get install libboost1.55-all-dev libssl-dev libcurl4-openssl-dev
install:
  - pip install tox
script:
  - tox
branches:
  only:
    - api
notifications:
  email:
    on_success: change
    on_failure: always
