sudo: false
language: cpp
compiler:
  - g++
env:
  - CMAKE_BUILD_TYPE=DEBUG CXX_VERSION=4.9
  - CMAKE_BUILD_TYPE=RELEASE CXX_VERSION=4.9
  - CMAKE_BUILD_TYPE=DEBUG CXX_VERSION=5
  - CMAKE_BUILD_TYPE=RELEASE CXX_VERSION=5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - deadsnakes
    packages:
      - libboost1.55-all-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - gcc-4.9
      - g++-4.9
      - gcc-5
      - g++-5
      - python-virtualenv
      - python2.7
      - python2.7-dev
      - python3.4
      - python3.4-dev
cache:
  apt: true
before_script:
  - wget -O /tmp/cmake.sh --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh
  - mkdir -p /tmp/usr
  - sh /tmp/cmake.sh --skip-license --prefix=/tmp/usr
  - virtualenv /tmp/venv
  - "/tmp/venv/bin/pip install tox"
script:
  - CXX=g++-${CXX_VERSION} /tmp/usr/bin/cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} .
  - make install
  - CPATH=${TRAVIS_BUILD_DIR}/install/include LIBRARY_PATH=${TRAVIS_BUILD_DIR}/install/lib
    LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/install/lib /tmp/venv/bin/tox
after_success:
  - coveralls
branches:
  only:
    - api
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: K/3UxGbJ5glGANIAluRPu9tAblqc8vIiTbhbKBh5Jvnhw4Xz37nddWV1EGlq+Ax8g1UkhxBFMAGKMJAzHbLnahkV/I6IdM0HvLdknoZlX6t9JwbkSgey2cu5rN2xqP0Q8I1MgnLzZfr3CEGGqHu/Vcb6Ux5+UiKYR94bRfqaREY=
