version: 3.0-{build}

environment:
  BOOST_ROOT: C:\Libraries\Boost

configuration:
  - Debug
  - Release

before_build:
  - cmd: cmake -G "Visual Studio 12 2013" -DBOOST_ROOT=%BOOST_ROOT% .

build:
  project: FreeLAN.sln
  parallel: true
  verbosity: normal

after_build:
  - msbuild INSTALL.vcxproj

test_script:
  - install\bin\freelan_tests
