version: 3.0-{build}

environment:
  BOOST_ROOT: C:\local\boost_1_58_0
  BOOST_DOWNLOAD_URL: http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.zip/download
  BOOST_ARCHIVE_NAME: boost_1_58_0.zip

  matrix:
    - CMAKE_GENERATOR: "Visual Studio 12 2013"
    - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"

configuration:
  - Debug
  - Release

install:
  - appveyor DownloadFile %BOOST_DOWNLOAD_URL%
  - dir
  - 7z x %BOOST_ARCHIVE_NAME%

before_build:
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DBOOST_ROOT=%BOOST_ROOT% .

build:
  project: FreeLAN.sln
  parallel: true
  verbosity: normal

after_build:
  - msbuild INSTALL.vcxproj

test_script:
  - install\bin\freelan_tests

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
