version: 2.1.{build}

shallow_clone: true

image: Visual Studio 2017

environment:
  matrix:
    - platform: x64
      ARCH_BITS: 64
    - platform: x86
      ARCH_BITS: 32

configuration:
  - Release
  - Debug

init:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%'

install:
  - cinst cmake
  - xcopy /I third-party\vcpkg\ports\miniupnpc c:\tools\vcpkg\ports\miniupnpc

before_build:
  - vcpkg install libiconv --triplet %PLATFORM%-windows-static
  - vcpkg install boost-asio boost-thread boost-system boost-program-options boost-filesystem boost-iostreams boost-random boost-foreach --triplet %PLATFORM%-windows-static
  - vcpkg install curl --triplet %PLATFORM%-windows-static
  - vcpkg install openssl --triplet %PLATFORM%-windows-static
  - vcpkg install miniupnpc --triplet %PLATFORM%-windows-static

build_script:
  - 'nmake -f Makefile.windows build_%CONFIGURATION%_%PLATFORM%'

branches:
    only:
        - master
        - vcpkg
