version: 3.0-{build}

environment:
  BOOST_ROOT: C:\Libraries\Boost

  matrix:
    - CMAKE_GENERATOR: "Visual Studio 12 2013"
    - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"

configuration:
  - Debug
  - Release

before_build:
  - cmd: cmake -G "%CMAKE_GENERATOR%" -DBOOST_ROOT=%BOOST_ROOT% .

build:
  project: FreeLAN.sln
  parallel: true
  verbosity: normal

after_build:
  - msbuild INSTALL.vcxproj

test_script:
  - install\bin\freelan_tests

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
