version: 3.0-{build}

branches:
  only:
    - api

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 12 2013"
      ARCHITECTURE: "x86"
    - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      ARCHITECTURE: "x64"

configuration:
  - Debug
  - Release

install:
  - C:\Python27\Scripts\pip install teapot
  - C:\Python27\Scripts\teapot build boost

cache:
  - third-party

before_build:
  - cmd: cmake -G "%CMAKE_GENERATOR%" .

build:
  project: FreeLAN.sln
  parallel: true
  verbosity: normal

after_build:
  - msbuild INSTALL.vcxproj

test_script:
  - install\bin\freelan_tests

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
